version: "3"

services:
  notifybot:
    build:
      context: .
      dockerfile: ./Dockerfile_Notifybot
    container_name: notifybot
    restart: unless-stopped
    links:
      - mosquitto:mosquitto
    volumes:
      - ./pkg:/pkg
      - ./main.go:/main.go
      - ./go.mod:/go.mod
      - ./go.sum:/go.sum
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MOSQUITTO_USERNAME}
      - MQTT_PASSWORD=${MOSQUITTO_PASSWORD}
      - FRIGATE_HOST=${FRIGATE_HOST}
      - FRIGATE_PORT=${FRIGATE_PORT}
      - TELEGRAM_KEY=${TELEGRAM_KEY}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    depends_on:
      - mosquitto

  mosquitto:
    build: .
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto
    container_name: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
